### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic-site#283]
#### TODO: Developer Preview Docs
- [ ] fix navbar styling
- [ ] fix styling for anything using v2 source (demo docs, button docs)
- [ ] use a different footer for each doc page
